# Generated by Django 5.1.3 on 2024-11-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='news.tag')),
            ],
        ),
    ]
