# Generated by Django 5.1.3 on 2024-11-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_catalogitem_logo_catalogitem_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
