# Generated by Django 5.1.3 on 2024-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_category_game_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='game_logos/', verbose_name='logo'),
        ),
    ]
